CREATE TABLE IF NOT EXISTS `calls_data` (
            `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
            `client_id` INT NOT NULL,
            `scenario` ENUM ('income', 'dropped') NOT NULL,
            `notification_name` VARCHAR(255) NOT NULL,
            `virtual_phone_number` VARCHAR(255) NOT NULL,
            `notification_time` TIMESTAMP NOT NULL,
            `advertising_campaign` VARCHAR(255) NOT NULL,
            `contact_phone_number` VARCHAR(255) NOT NULL,
            `visitor_id` INT NOT NULL,
            `search_query` VARCHAR(255) NOT NULL,
            `communication_number` VARCHAR(255) NOT NULL,
            `visitor_is_new` BOOLEAN NOT NULL,
            `search_engine` VARCHAR(255) NOT NULL,
            `call_session_id` INT NOT NULL,
            `call_source` VARCHAR(255),
            `direction` VARCHAR(255),
            `talk_time_duration` INT,
            `total_time_duration` INT,
            `wait_time_duration` INT,
            `is_lost` BOOLEAN,
            FOREIGN KEY (client_id) REFERENCES visitors_info (id)
)